version: '3.7'

services:
  gateway-api:
    image: restaurant-gateway
    build: ./gateway/restaurant-gateway/
    ports: 
      - "8080:8080"
    depends_on: 
      - identity-api
      - menu-api
      - basket-api
      - order-api

     
  identity-api:
    image: restaurant/identity
    build: ./services/identity.api/
    ports:
       - "5000:5000"
    depends_on:
       - pgsql

  menu-api:
    image: restaurant/menu
    build: ./services/menu.api/
    ports:
       - "5100:5000"
    depends_on:
       - pgsql
  
  basket-api:
    image: restaurant/basket
    build: ./services/basket.api/
    ports:
      - "5200:5200"
    depends_on:
      - redis

  order-api:
    image: restaurant/order
    build: ./services/order.api
    ports:
      - "5300:8080"
    depends_on:
      - pgsql

  pgsql:
    image: postgres:alpine
  
  redis:
    image: redis:alpine