version: '3.7'

services:
  identity-api:
    image: restaurant/identity
    build: ./services/netcore/Identity.API/
    ports:
       - "5000:5000"
    depends_on:
       - identity-data

  menu-api:
    image: restaurant/menu
    build: ./services/netcore/Menu.API/
    ports:
       - "5100:5100"
    depends_on:
       - menu-data
  
  basket-api:
    image: restaurant/basket
    build: ./services/go/src/basket.api/
    ports:
      - "5200:5200"
    depends_on:
      - basket-data

  order-api:
    image: restaurant/order
    build: ./services/java/order.api/
    ports:
      - "5300:5300"
    depends_on:
      - order-data

  menu-data:
    image: postgres:alpine
  
  identity-data:
    image: postgres:alpine

  basket-data:
    image: redis:alpine
  
  order-data:
    image: restaurant/order_database
    build: 
      context: ./services/java/order.api/
      dockerfile: Dockerfile-database