version: '3.7'

services:
  menu-api:
    image: restaurant/menu
    build: ./Services/Menu/Menu.API/
    ports:
       - "8080:80"
    depends_on:
       - menu-data
    

  menu-data:
    image: postgres:10.1