version: '3.7'

services:
  catalog-api:
    image: restaurant/catalog-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgres://admin:Passw0rd!@catalog-db:5432/catalogdb
      - ROCKET_ADDRESS=0.0.0.0
      - ROCKET_PORT=8000
    depends_on:
      - catalog-db
    healthcheck:
      test: curl --fail http://127.0.0.1 || exit 1
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 10s
  
  catalog-db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=Passw0rd!
      - POSTGRES_USER=admin
      - POSTGRES_DB=catalogdb
      