version: 1.0.{build}
branches:
  only:
  - master
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\Restaurant.Server.Api.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- cmd: nuget.exe restore Restaurant.Server.sln
build:
  project: Restaurant.Server.sln
  verbosity: minimal
test:
  assemblies:
    only:
    - Restaurant.Server.Api.Tests.dll