# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - develop
  paths:
    include:
    - src/Client/*
    - azure-pipelines.yml

jobs:
- job: Android
  pool:
    vmImage: 'windows-latest'
  variables:
    buildConfiguration: 'Release'
    outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'
  steps:
  - task: NuGetToolInstaller@0
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/Restaurant.Client.sln'
  - task: XamarinAndroid@1
    inputs:
      projectFile: '**/Restaurant.Droid.csproj'
      outputDirectory: '$(outputDirectory)'
      configuration: '$(buildConfiguration)'
      msbuildVersionOption: 'latest'
      msbuildArchitectureOption: 'x64'
      jdkOption: 'JDKVersion'
      msbuildArguments: /p:JavaSdkDirectory="$(JAVA_HOME)/"

- job: iOS
  pool:
    vmImage: 'macOS-latest'
  variables:
    buildConfiguration: 'Release'
  steps:
  - bash: |
      SYMLINK=6_0_0
      xcodeRoot=/Applications/Xcode_10.3.app
      MONOPREFIX=/Library/Frameworks/Mono.framework/Versions/$SYMLINK
      echo "##vso[task.setvariable variable=DYLD_FALLBACK_LIBRARY_PATH;]$MONOPREFIX/lib:/lib:/usr/lib:$DYLD_LIBRARY_FALLBACK_PATH"
      echo "##vso[task.setvariable variable=PKG_CONFIG_PATH;]$MONOPREFIX/lib/pkgconfig:$MONOPREFIX/share/pkgconfig:$PKG_CONFIG_PATH"
      echo "##vso[task.setvariable variable=PATH;]$MONOPREFIX/bin:$PATH"
      echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'${xcodeRoot};sudo xcode-select --switch ${xcodeRoot}/Contents/Developer"
      sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_0_0
  - task: NuGetToolInstaller@0
  - task: NuGetCommand@2
    inputs:
      restoreSolution: '**/Restaurant.Client.sln'
  - task: XamariniOS@2
    inputs:
      solutionFile: '**/Restaurant.iOS.csproj'