---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: dashboard-app
---
apiVersion: v1
kind: Service
metadata:
  name: menu-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: menu-api



---
apiVersion: v1
kind: Service
metadata:
  name: order-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: 8090
  selector:
    app: order-api

---
apiVersion: v1
kind: Service
metadata:
  name: identity-api
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
  selector:
    app: identity-api