version: '3.7'

services:
  nginx:
    environment:
      - IDENTITY_URL=http://identity-api
      - BASKET_URL=http://basket-api:5200
      - ORDER_URL=http://order-api:8090
      - CATALOG_URL=http://catalog-api:8000
      - DASHBOARD_URL=http://dashboard-app

  order-api:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pgsql:5432/orderdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=Passw0rd!
      - IDENTITY_URL_PUB=http://localhost:8080/identity
      - IDENTITY_URL=http://identity-api
      - BASKET_URL==http://basket-api:5200

  basket-api:
    environment:
      - REDIS_HOST=redis
      - IDENTITY_URL=http://identity-api
      - IDENTITY_URL_PUB=http://localhost:8080/identity
      - BASE_PATH=/basket

  # catalog-api:
  #   environment:
  #     - DATABASE_URL=postgres://admin:Passw0rd!@catalog-db:5432/catalogdb
  #     - ROCKET_ADDRESS=0.0.0.0
  #     - ROCKET_PORT=8000

  pgsql:
    environment:
      - POSTGRES_PASSWORD=Passw0rd!
      - POSTGRES_USER=admin
      - PGDATA=/pg
      - POSTGRES_DB=orderdb

  catalog-db:
    environment:
      - POSTGRES_PASSWORD=Passw0rd!
      - POSTGRES_USER=admin
      - POSTGRES_DB=catalogdb

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DB_HOST=pgsql
      - DB_NAME=identity_database
      - DB_USER=admin
      - DB_PASSWORD=Passw0rd!
      - PATH_BASE=/identity
      - MENU_API_URL=http://localhost:8080/menu
      - ORDER_API_URL=http://localhost:8080/order
      - BASKET_API_URL=http://localhost:8080/basket
      - DASHBOARD_APP_URL=http://localhost:8080/dashboard
      - IDENTITY_URL_PUB=http://localhost:8080/identity
