name: "Bumping SemVer"
description: "Bumping SemVer"
inputs:
  service-name: 
    description: 'Service name'
    required: true

outputs:
  current-version: 
    description: "Current Version number"
    value: ${{ steps.version.outputs.current-number }}
  new-version:
    description: "Next bumped Version number"
    value: ${{ steps.version.outputs.next-number }}

runs:
  using: "composite"
  steps:
    - id: version
      run: | 
        CURR_VER=$(cat ${{ inputs.service-name }}/version)

        chmod +x ./src/scripts/semver
        NEW_VER=$(./src/scripts/semver bump patch $CURR_VER)
        echo $NEW_VER > ${{ inputs.service-name }}/version

        echo ::set-output name=current-number::${CURR_VER}
        echo ::set-output name=next-number::${NEW_VER}

      shell: bash
      