---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dashboard-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: dashboard-app
    spec:
      containers:
      - image: jurabek/dashboard
        imagePullPolicy: Always
        name: dashboard-app
        ports:
        - containerPort: 80
        resources:

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: basket-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: basket-api
    spec:
      containers:
      - image: jurabek/basket
        imagePullPolicy: Always
        name: basket-api
        ports:
        - containerPort: 5200
        env:
        - name: IDENTITY_URL
          valueFrom:
            configMapKeyRef:
              name: internal-urls
              key: identity
        - name: REDIS_HOST
          value: redis-data:6379
        - name: BASE_PATH
          value: /basket
        resources:

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: identity-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: identity-api
    spec:
      containers:
      - name: identity-api
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        image: jurabek/identity
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: OrchestrationType
          value: k8s
        - name: PATH_BASE
          value: /identity
        - name: BASKET_API_URL
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: basket_pub
        - name: IDENTITY_URL_PUB
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: identity_pub
        - name: MENU_API_URL
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: menu_pub
        - name: ORDER_API_URL
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: order_pub
        - name: DASHBOARD_URL
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: dashboard_pub
        - name: ConnectionStrings__IdentityConnectionString
          valueFrom:
            configMapKeyRef:
              name: local-config
              key: identity__ConnectionString
        resources:
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: menu-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: menu-api
    spec:
      containers:
      - name: menu-api
        image: jurabek/menu
        imagePullPolicy: Always
        ports:
          - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: PATH_BASE
          value: /menu
        - name: OrchestrationType
          value: k8s
        - name: ConnectionStrings__MenuDatabaseConnectionString
          valueFrom:
           configMapKeyRef:
             name: local-config
             key: menu__ConnectionString
        - name: IDENTITY_URL_PUB
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: identity_pub
        - name: IDENTITY_URL
          valueFrom:
            configMapKeyRef:
              name: internal-urls
              key: identity
        resources:
        
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: order-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - image: jurabek/order
        imagePullPolicy: Always
        name: order-api
        ports:
          - containerPort: 8090
        env:
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: /order
        - name: IDENTITY_URL_PUB
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: identity_pub
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: local-config
              key: order__DataSourcePassword
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: local-config
              key: order__DataSourceUrl
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: local-config
              key: order__DataSourceUserName 
        resources:


---
        # livenessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8090
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 5
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /actuator/health
        #     port: 8090
        #   initialDelaySeconds: 10
        #   timeoutSeconds: 5
        #   periodSeconds: 10