apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: frontend
  name: restaurant-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: local-restaurant-app
  - http:
      paths:
      - path: /menu
        backend:
          serviceName: menu-api
          servicePort: 80
      - path: /basket
        backend:
          serviceName: basket-api
          servicePort: 80
      - path: /identity
        backend:
          serviceName: identity-api
          servicePort: 80
      - path: /order
        backend:
          serviceName: order-api
          servicePort: 80