apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: frontend
  name: restaurant-ingress
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"  
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: gateway-api
          servicePort: 80