apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

resources:
- deployment.yaml
- service.yaml
- virtual-service.yaml

configMapGenerator:
- envs:
  - config.env
  name: menu-api

secretGenerator:
- envs:
  - .env.secret
  name: menu-api

images:
- name: catalog-api
  newName: ghcr.io/chayxana/catalog-api
  newTag: 0.0.4
- name: menu-api
  newName: ghcr.io/chayxana/menu
  newTag: 1.0.1
