apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - image: jurabek/order
        imagePullPolicy: IfNotPresent
        name: order-api
        ports:
          - containerPort: 8090
        env:
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: /order
        - name: IDENTITY_URL_PUB
          valueFrom:
            configMapKeyRef:
              name: endpoints
              key: identity_pub
        - name: IDENTITY_URL
          valueFrom:
            configMapKeyRef:
              name: internal-urls
              key: identity
        - name: BASKET_URL
          valueFrom:
            configMapKeyRef:
              name: internal-urls
              key: basket
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: local-config
              key: order__DataSourcePassword
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            configMapKeyRef:
              name: local-config
              key: order__DataSourceUrl
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: local-config
              key: order__DataSourceUserName
        readinessProbe:
          httpGet:
            path: /order/health
            port: 8090
          initialDelaySeconds: 30
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /order/health
            port: 8090
          initialDelaySeconds: 60
          timeoutSeconds: 3
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"