#Will start the gateway server @8080
server:
  port: 8080

spring:
  application:
    name: restaurant-gateway
 
#Ribbon is auto integrated with Zuul and for this exercise we are not using that.
ribbon:
  eureka:
    enabled: enabled
  ReadTimeout: 60000
  ConnectTimeout: 60000
 
#Zuul routes.

zuul:
  routes:
    menu:
      path: /menu/**
      serviceId: menu-service
      sensitiveHeaders:
    order:
      path: /order/**
      serviceId: order-service
    identity:
      path: /identity/**
      serviceId: identity-service
      sensitiveHeaders:
    basket:
      path: /basket/**
      serviceId: basket-service
  host:
        connect-timeout-millis: 60000
        socket-timeout-millis: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  