#Will start the gateway server @8080
server:
  port: 8080

spring:
  application:
    name: restaurant-gateway
 
#Ribbon is auto integrated with Zuul and for this exercise we are not using that.
ribbon:
  eureka:
    enabled: enabled
 
#Zuul routes. Here for /student path, we are routing to localhost:8090 with extra path after that.
# urls will be ovveriding from docker-compose or kubernetes

zuul:
  routes:
    menu:
      path: /menu/**
      serviceId: menu-service
    order:
      path: /order/**
      serviceId: order-service
    identity:
      path: /identity/**
      serviceId: identity-service
    basket:
      path: /basket/**
      serviceId: basket-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"