  
name: basket-api

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
    paths:
    - './src/Server/services/basket.api/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: jurabek/golang:1.11-alpine
    steps:
    - uses: actions/cache@v1
      with:
        path: /go/pkg/mod
        key: ${{ runner.os }}-go-basket-api
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/checkout@v1
    - name: build artifact 
      run: |
        chmod -R +x ci/
        ci/build.sh basket_api
        ls
      working-directory: ./src/Server/
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jurabek/basket
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile.ci
        workdir: ./src/Server/services/basket.api

    - name: Upload basket-api artifact
      uses: actions/upload-artifact@v1
      with:
        name: basket_api
        path: ./src/Server/services/basket.api/basket.api
  docker-build-and-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Download basket-api artifact
      uses: actions/download-artifact@v1
      with:
        name: basket_api
    - name:
      shell: bash
      run: |
        ls
        cd basket_api
        ls