  
name: basket-api

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
    paths:
    - './src/backend/services/basket.api/**'
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x

    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Setup cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/basket.api/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    
    - name: Build & QA 
      run: |
        chmod -R +x scripts/
        scripts/build.sh basket_api
      working-directory: ./src/backend/
    
    - name: Test & QA
      run: |
        chmod -R +x scripts/
        scripts/qa.sh basket_api
      working-directory: ./src/backend/
    
    - name: Upload basket-api artifact
      uses: actions/upload-artifact@v1
      with:
        name: basket_api
        path: ./src/backend/services/basket.api/basket.api
      if: matrix.os == 'ubuntu-latest'
    
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        projectBaseDir: ./src/backend/services/basket.api
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.BASKET_API_SONAR_TOKEN }}
      if: matrix.os == 'ubuntu-latest'
  
  docker-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download basket-api artifact
      uses: actions/download-artifact@v1
      with:
        name: basket_api
    - name: Copy artifact to working directory
      shell: bash
      run: |
        cp basket_api/basket.api ./src/backend/services/basket.api/
    - name: Publish docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jurabek/basket
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: release.Dockerfile
        workdir: ./src/backend/services/basket.api

