  
name: basket-api

on:
  push:
    branches:
    - develop
    paths:
    - './src/Server/services/basket.api/**'
  pull_request:
    branches:
    - develop
    paths:
    - './src/Server/services/basket.api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: jurabek/golang:1.11-alpine

    steps:
    - uses: actions/checkout@v1
    - run: |
        chmod -R +x ci/
        ci/build.sh basket_api
        echo $GOPATH
        cd $GOPATH
        ls
      working-directory: ./src/Server/
    