  
name: basket-api

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
    paths:
    - './src/Server/services/basket.api/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: jurabek/golang:1.11-alpine
    steps:
    - uses: actions/cache@v1
      with:
        path: /go/pkg/mod
        key: ${{ runner.os }}-go-basket-api
        restore-keys: |
          ${{ runner.os }}-go-
    - uses: actions/checkout@v1
    - name: Build artifact 
      run: |
        chmod -R +x ci/
        ci/build.sh basket_api
      working-directory: ./src/Server/
    - name: Upload basket-api artifact
      uses: actions/upload-artifact@v1
      with:
        name: basket_api
        path: ./src/Server/services/basket.api/basket.api
  
  docker-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Download basket-api artifact
      uses: actions/download-artifact@v1
      with:
        name: basket_api
    - name: Copy artifact to working directory
      shell: bash
      run: |
        cp basket_api/basket.api ./src/Server/services/basket.api/
    - name: Publish docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jurabek/basket
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile.ci
        workdir: ./src/Server/services/basket.api