  
name: basket-api

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
    paths:
    - './src/Server/services/basket.api/**'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: jurabek/golang:1.11-alpine

    steps:
    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-basket-api
        restore-keys: |
          ${{ runner.os }}-go-basket-api
    - uses: actions/checkout@v1
    - run: |
        chmod -R +x ci/
        ci/build.sh basket_api
      working-directory: ./src/Server/
    
