  
name: basket-api

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
    # paths:
    # - './src/Server/services/basket.api/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13.x
    - name: Setup cache
      uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: go-${{ hashFiles('**go.sum') }}
        restore-keys: |
          go-
    
    - uses: actions/checkout@v1
    - name: Build & QA 
      run: |
        chmod -R +x ci/
        ci/build.sh basket_api
        ci/qa.sh basket_api
      working-directory: ./src/Server/
    
    - name: Upload basket-api artifact
      uses: actions/upload-artifact@v1
      with:
        name: basket_api
        path: ./src/Server/services/basket.api/basket.api

    - name: SonarCloud Scan
      uses: jurabek/sonar-scanner-github-actions@master
      with:
        projectBaseDir: ./src/Server/services/basket.api
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.BASKET_API_SONAR_TOKEN }}
  
  docker-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download basket-api artifact
      uses: actions/download-artifact@v1
      with:
        name: basket_api
    - name: Copy artifact to working directory
      shell: bash
      run: |
        cp basket_api/basket.api ./src/Server/services/basket.api/
    - name: Publish docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jurabek/basket
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: Dockerfile.ci
        workdir: ./src/Server/services/basket.api