name: identity-api

on:
  push:
    branches:
    - develop
    paths:
    - './src/backend/services/identity.api/**'
  pull_request:
    branches:
    - develop
    paths:
    - './src/backend/services/identity.api/**'

jobs:
  my_job:
    name: build and test
    runs-on: ubuntu-18.04
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: 2.2.104
      - uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: identity-api-dotnet-cache-key
          restore-keys: |
            identity-api-dotnet-cache-key
      - uses: actions/checkout@v1
      - name: Build & QA 
        run: |
          echo $PATH
          chmod -R +x ci/
          ci/build.sh identity_api
          # ci/qa.sh identity_api
        working-directory: ./src/backend/
