name: menu-api

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
    paths:
    - './src/backend/services/menu.api/**'

jobs:
  build-and-test:
    name: build and test
    runs-on: ubuntu-18.04
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: 3.1.100 
      - uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: menu-api-dotnet-cache-key
          restore-keys: |
            menu-api-dotnet-cache-key
      - uses: actions/checkout@v1
      - name: Build & QA
        run: |
          echo $PATH
          chmod -R +x ci/
          ci/build.sh menu_api
          ci/qa.sh menu_api
        working-directory: ./src/backend/
        env:
          SONAR_TOKEN: ${{ secrets.MENU_API_SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload menu-api artifact
        uses: actions/upload-artifact@v1
        with:
          name: menu_api
          path: ./src/backend/services/menu.api/menu-api-release
  docker-push:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Download basket-api artifact
      uses: actions/download-artifact@v1
      with:
        name: menu_api
    - name: Copy artifact to working directory
      shell: bash
      run: |
        cp menu-api-release ./src/backend/services/menu.api/
    - name: Publish docker image
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: jurabek/menu
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: release.Dockerfile
        workdir: ./src/backend/services/menu.api

