name: menu-api

on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop
    paths:
    - './src/backend/services/menu.api/**'

jobs:
  my_job:
    name: build and test
    runs-on: ubuntu-18.04
    steps:
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.4.0
        with:
          dotnet-version: 3.1.100 
      - uses: actions/cache@v1
        with:
          path: ~/.nuget/packages
          key: menu-api-dotnet-cache-key
          restore-keys: |
            menu-api-dotnet-cache-key
      - uses: actions/checkout@v1
      - name: Build
        run: |
          echo $PATH
          chmod -R +x ci/
          ci/build.sh menu_api
        working-directory: ./src/backend/
      - uses: jurabek/dotnet-sonarscanner-github-actions@master
      - name: QA
        run: |
          echo "Started sonar scanner"
          ci/qa.sh menu_api
          echpo "Finished"
        working-directory: ./src/backend/
        env:
          SONAR_TOKEN: ${{ secrets.MENU_API_SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
