name: order-api

on:
  push:
    branches:
      - develop
    paths:
      - "src/backend/services/order-api/**"
      - ".github/workflows/order-api.yml"
  pull_request:
    branches:
      - develop
    paths:
      - "src/backend/services/order-api/**"
      - ".github/workflows/order-api.yml"


jobs:
  pull-request-build:
    if: github.ref != 'refs/heads/develop'
    uses: ./.github/workflows/build-release.yml
    with:
      service-name: order-api
    secrets: inherit

  build-release:
    if: github.ref == 'refs/heads/develop'
    uses: ./.github/workflows/build-release.yml
    with:
      service-name: order-api
      docker-file: native.Dockerfile
    secrets: inherit


  deploy:
    if: github.ref == 'refs/heads/develop'
    needs:
      - build-release
    uses: ./.github/workflows/deploy.yml
    with:
      service-name: order-api
      version: ${{ needs.build-release.outputs.new-version }}
