name: payment-api

on:
  push:
    branches:
    - develop
    paths:
    - "src/backend/services/payment-api/**"
    - ".github/workflows/payment-api.yml"
  pull_request:
    branches:
    - develop
    paths:
    - "src/backend/services/payment-api/**"
    - ".github/workflows/payment-api.yml"

jobs:
  payment-api-ci:
    uses: ./.github/workflows/build-release.yml
    with:
      service-name: payment-api
    secrets: inherit