name: web-app

on:
  push:
    branches:
      - develop
    paths:
      - 'src/backend/web/web.client/web-app/**'
      - '.github/workflows/web-app.yml'
  pull_request:
    branches:
      - develop
    paths:
      - 'src/backend/web/web.client/web-app/**'
      - '.github/workflows/web-app.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '8.x'
    
    - name: Install Packages
      run: npm install
      working-directory: ./src/backend/web/web.client/web-app/

    - name: Build
      run: npm run build --if-present
      working-directory: ./src/backend/web/web.client/web-app/
      
      env:
        CI: true