name: web-app

on:
  push:
    branches:
      - develop
    paths:
      - './src/backend/web/web.client/web-app/**'
  pull_request:
    branches:
      - develop
    paths:
      - './src/backend/web/web.client/web-app/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install Packages
      run: npm install
      working-directory: ./src/backend/web/web.client/web-app/

    - name: Build
      run: npm run build --if-present
      working-directory: ./src/backend/web/web.client/web-app/
    
    - name: Test
      run: npm test
      working-directory: ./src/backend/web/web.client/web-app/
      
      env:
        CI: true